services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: custom_root
      POSTGRES_PASSWORD: custom_password
      POSTGRES_DB: book-quiz-db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
